//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sonDeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int ID { get; set; }
        public int personel_ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string TC { get; set; }
        public string Telefon { get; set; }
        public string Adres { get; set; }
        public int Maas { get; set; }
        public string Unvan { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
