//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sonDeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disiplin
    {
        public int disiplin_ID { get; set; }
        public string konu { get; set; }
        public string aciklama { get; set; }
        public System.DateTime Tarih { get; set; }
        public Nullable<int> Ogrenciler_ID { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
