//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sonDeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyurular
    {
        public int Duyuru_ID { get; set; }
        public string Duyuru { get; set; }
        public System.DateTime Tarih { get; set; }
        public string Konu { get; set; }
    }
}
