//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sonDeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giderler
    {
        public int gider_ID { get; set; }
        public string elektrik { get; set; }
        public string su { get; set; }
        public string dogalgaz { get; set; }
        public string yemekhane { get; set; }
        public string calisan_maas { get; set; }
        public System.DateTime tarih { get; set; }
    }
}
