//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sonDeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class GirisCikis
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> YurtGiris { get; set; }
        public Nullable<System.DateTime> YurtCikis { get; set; }
        public Nullable<System.DateTime> YemekhaneGiris { get; set; }
        public Nullable<System.DateTime> YemekhaneCikis { get; set; }
        public Nullable<System.DateTime> EtutGiris { get; set; }
        public Nullable<System.DateTime> EtutCikis { get; set; }
        public Nullable<int> Ogrenciler_ID { get; set; }
    
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
