//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sonDeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public bool isAdmin { get; set; }
    
        public virtual Calisanlar Calisanlar { get; set; }
        public virtual Ogrenciler Ogrenciler { get; set; }
    }
}
