//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sonDeneme
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenciler()
        {
            this.Disiplin = new HashSet<Disiplin>();
            this.GirisCikis = new HashSet<GirisCikis>();
        }
    
        public int ID { get; set; }
        public Nullable<int> oda_oda_ID { get; set; }
        public int Ogrenci_ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string TC { get; set; }
        public string Telefon { get; set; }
        public string Veli_Tel { get; set; }
        public string Kacini_Sinif { get; set; }
        public string Adres { get; set; }
        public string KartID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disiplin> Disiplin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GirisCikis> GirisCikis { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Oda Oda { get; set; }
    }
}
